main:

  project_name: data-engineering-pipeline
  experiment_name: development
  steps: all
data_upload_S3:
  # The path towards your dataset to be uploaded
  path: "D:/data-engineering-pipeline/data"

  # The bucket name for the file to be uploaded
  bucket_name: "data-engineering-pipeline"

  # The prefix of the bucket data to be uploaded into
  prefix_name: "FHIR-data"
data_upload:

  bucket_path: s3://data-engineering-pipeline/FHIR-data


data_processing:

