name: db_upload
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.0.3
  - requests
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.31
      - boto3==1.21.12
      - pymongo
      - pymongo[srv]
      - git+https://github.com/arkaan27/data-engineering-pipeline.git#egg=Utils&subdirectory=src/components
