wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.10
    t:
      3:
      - 2
      4: 3.9.10
      5: 0.10.31
      8:
      - 1
      - 5
