wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    t:
      4: 3.10.2
      5: 0.10.31
      8:
      - 5
directory_path:
  desc: null
  value: https://github.com/arkaan27/data-engineering-pipeline.git#data
output_artifact:
  desc: null
  value: raw_data
output_description:
  desc: null
  value: Component to upload the data to Weights and Biases
output_type:
  desc: null
  value: data_upload
